---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        count_sum: "{{ hostvars[item]['ansible_net_interfaces.Ethernet1/1.mtu'] + count_sum | default(0) }}"
      with_items: "{{ ansible_play_hosts }}"