---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: configure interface
      eos_command:
        commands: show version
        provider:
          transport: eapi
          validate_certs: "{{ validate_SSL_certs | default('no') }}"