- hosts: all
  gather_facts: no
  connection: network_cli
  become: yes

  tasks:
    - asa_config:
        lines:
          - network-object host 10.80.30.18
          - network-object host 10.80.30.19
          - network-object host 10.80.30.20
        parents: ['object-group network OG-MONITORED-SERVERS']
