---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - import_role:
        name: ciscopre
      when:
        - '"nxos" in ansible_network_os'

    - import_role:
        name: nxos_precheck
      when:
        - '"nxos" in ansible_network_os'