---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: collect output from ios device
      ios_command:
        host: "{{ inventory_hostname }}"
        commands:
          - show version
          - show interface
          - show running-config all
      register: output

    - name: set config fact
      set_fact:
        config: "{{ output.stdout[2] }}"

    - name: set config_lines fact
      set_fact:
        config_lines: "{{ config.split('\n') }}"

    - name: Remove Netflow IP
      ios_config:
        lines: no {{ item }}
        host: "{{ inventory_hostname }}"
      with_items: "{{ config_lines | select('match', 'ip flow-export destination *') | list }}"

    - name: Change netflow IP
      ios_config:
        lines:
          - ip flow-export destination {{ netflow_ip }} {{ netflow_port }}
        host: "{{ inventory_hostname }}"