- hosts: all
  gather_facts: no
  connection: local
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
    - panos_commit:
        ip_address: "{{ inventory_hostname }}"
        username: admin
        password: cisco
