- hosts: all
  gather_facts: no
  connection: local
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
    - name: Bootstrap a host without python2 installed
      raw:
        - configure
        - set mgt-config users test1 password test1

    - name: Bootstrap a host without python2 installed
      raw: configure set mgt-config users test1 permissions role-based auditadmin

    - panos_commit:
        ip_address: "{{ inventory_hostname }}"
        username: admin
        password: cisco
