---
- hosts: all
  connection: local
  gather_facts: no
  
  tasks:
    - name: add acl lines
      nxos_config:
        lines:
          - switchport mode trunk
          - switchport trunk native vlan 20
          - switchport trunk allowed vlan 50-51
        parents: interface gigabitethernet 0/0