---
- hosts: all
  connection: local
  gather_facts: no
  
  tasks:
  - name: test task
    ios_command:
      host: '{{ inventory_hostname }}'
      commands:
        - show version
        - show log
        - show ip int br
