---
- name: configure interface
  ios_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    enabled: True
    provider:
      authorize: no
  with_items: "{{ l2_interfaces }}"


