---
- name: configure interface
  ios_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    enabled: True
    provider:
      authorize: no
  with_items: "{{ l2_interfaces }}"

- name: configure name servers
  ios_system:
    name_servers: "{{ item.servers }}"
  with_items: "{{ name_servers }}"

- name: configure ntp servers
  ios_config:
    lines:
      - ntp server "{{ item.ntp }}"
    provider:
      authorize: no
  with_items: "{{ ntp_servers }}"
