---
- name: show commands
  nxos_command:
    host: "{{ inventory_hostname }}"
    commands:
      - show version
      - show interface
      - show running-config all
      - show ip interface brief vrf all | include {{ ansible_host }}
  register: output

- name: set hostname fact
  set_fact:
    hostname: "{{ output.stdout[0] | regex_findall('\\s+Device name:\\s+(\\S+)') | first }}"

- name: set interfaces fact
  set_fact:
    interfaces: "{{ output.stdout[1] | regex_findall('\n([E|L|P|V]\\S+)') }}"

- name: set version fact
  set_fact:
    version: "{{ output.stdout[0] | regex_findall('(system|NXOS):\\s+version\\s+(\\S+)') | first }}"

- name: set config fact
  set_fact:
    config: "{{ output.stdout[2] }}"

- name: set config_lines fact
  set_fact:
    config_lines: "{{ config.split('\n') }}"

- block:
    - name: Default NTP
      nxos_config:
        lines: no {{ item }}
        host: "{{ inventory_hostname }}"
      with_items: "{{ config_lines | select('match', 'ntp *') | list }}"
      when:
        - item ne 172.16.1.1
        - item ne 172.16.1.75
        - item ne 172.16.1.200
        - item ne 172.16.1.177

- name: Check compliance
  nxos_config:
    host: '{{ inventory_hostname }}'
    src: "{{ playbook_dir }}/roles/nxos_compliance/vars/nxos.j2"
    transport: cli
