---
- name: Set Interface Description
  nxos_config:
    transport: nxapi
    host: "{{ inventory_hostname }}"
    lines:
      - interface {{ interface_port }} description {{ interface_description }}