---
- name: collect output from nxos device
  nxos_command:
    host: "{{ inventory_hostname }}"
    commands:
      - show version
      - show interface
      - show running-config all
      - show ip interface brief vrf all | include {{ ansible_host }}
  register: output

# common facts
#

- name: set hostname fact
  set_fact:
    hostname: "{{ output.stdout[0] | regex_findall('\\s+Device name:\\s+(\\S+)') | first }}"

- name: set interfaces fact
  set_fact:
    interfaces: "{{ output.stdout[1] | regex_findall('\n([E|L|P|V]\\S+)') }}"

- name: set version fact
  set_fact:
    version: "{{ output.stdout[0] | regex_findall('(system|NXOS):\\s+version\\s+(\\S+)') | first }}"

- name: set config fact
  set_fact:
    config: "{{ output.stdout[2] }}"

- name: set config_lines fact
  set_fact:
    config_lines: "{{ config.split('\n') }}"

- name: display backup_file path
  debug: config_lines

- name: Port-channel Check
  nxos_command:
    commands:
      - show interface port-channel{{ port }}
    wait_for:
      - result[0] contains "port-channel{{ port }} is down"

- name: BFD Check
  nxos_command:
    commands:
      - show bfd neighbors interface port-channel{{ port }}
#    wait_for:
#      - result[0] contains

- name: Auto Cable Testing
  nxos_command:
    commands:
      - show interface {{ interface_add }} description
    wait_for:
      - result[0] contains "Auto_Cable_Testing"

- name: BGP check
  nxos_command:
    commands:
      - show bgp ipv4 unicast neighbors {{ bgp_ip_address }} | inc "BGP state"
    wait_for:
      - result[0] contains "BGP state = Shut"