---
- name: Backup fortinet
  fortios_address:
    host: "{{ inventory_hostname }}"
    username: admin
    password: admin
    state: present
    name: "google_dns"
    type: ipmask
    value: 8.8.8.8