---
- name: copy boot file from ansible controller to a network device
  net_put:
    src: "{{ playbook_dir }}/roles/iosupgrade_3750/vars/c3750-ipservicesk9-mz.122-55.SE11.bin"
    protocol: scp
    dest: flash:c3750-ipservicesk9-mz.122-55.SE11.bin
    mode: binary

- name: configure bootup image
  ios_config:
    lines:
      - boot system c3750-ipservicesk9-mz.122-55.SE11.bin
    save_when: changed

- name: reload device
  ios_command:
    commands:
      - command: 'reload'
        prompt: 'Proceed with reload\? \[confirm\]'
        answer: y

- name: Wait 300 seconds, but only start checking after 60 seconds
  wait_for_connection:
    delay: 60
    timeout: 300

- name: show boot
  ios_config:
    lines:
      - show boot