---
#- name: ASSIGN ANYCAST GATEWAY
#  nxos_overlay_global:
#    anycast_gateway_mac: "DEAD.BEEF.CAFE"
#  transport: cli

- name: DNS SERVER HOST CONFIGURATION
  nxos_system:
    name_servers:
      - { server: 5.232.32.63, vrf: management}
    lookup_source: mgmt0

#- name: Ensure BGP ASN exists
#  nxos_bgp:
#    asn: "{{ bgp_asn }}"
#    router_id: "{{ bgp_router_id }}"
#    state: present

- name: set port MTU
  nxos_system:
    system_mtu: 9216