---
- name: collect output from nxos device
  nxos_command:
    host: "{{ inventory_hostname }}"
    commands:
      - show version
      - show interface
      - show running-config all
      - show ip interface brief vrf all | include {{ ansible_host }}
  register: output

# common facts

#

- name: set hostname fact
  set_fact:
    hostname: "{{ output.stdout[0] | regex_findall('\\s+Device name:\\s+(\\S+)') | first }}"

- name: set interfaces fact
  set_fact:
    interfaces: "{{ output.stdout[1] | regex_findall('\n([E|L|P|V]\\S+)') }}"

- name: set version fact
  set_fact:
    version: "{{ output.stdout[0] | regex_findall('(system|NXOS):\\s+version\\s+(\\S+)') | first }}"

- name: set config fact
  set_fact:
    config: "{{ output.stdout[2] }}"

- name: set config_lines fact
  set_fact:
    config_lines: "{{ config.split('\n') }}"

- debug:
    msg: "START cisco-nxos.yml"

- block:
    - name: Get ipv6 interface info
      nxos_command:
        host: "{{ inventory_hostname }}"
        commands:
          - show ipv6 interface Lo0
      register: ipv6_interface

    - debug:
        var: ipv6_interface
        verbosity: 3

    - name: Default NTP
      nxos_config:
        lines: no {{ item }}
        host: "{{ inventory_hostname }}"
      with_items: "{{ config_lines | select('match', 'ntp *') | list }}"
      when: "(item not in item.ntp_server)"

    - name: add ntp servers
      nxos_config:
        host: '{{ inventory_hostname }}'
        transport: cli
        lines:
          - ntp server {{ item.ntp_server }}
      with_items: {{ ntp_servers }}

- name: configure the motd banner
  nxos_banner:
    banner: motd
    text: |
      this is my motd banner
      that contains a multiline
      string
    state: present
